[tool.poetry]
name = "m4-regex"
version = "0.1.0"
description = ""
authors = ["James Turk <dev@jamesturk.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
jupyterlab = "^4.0.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
